### ISSUE TITLE
Crearea NavBar

### ISSUE THREAD

**Issue by Staycoo10** [Staycoo10/RoyalSudio#5]
Task: Dezvoltarea și implementarea barei de navigare (NavBar) pentru a facilita navigarea pe site.
Descriere: Crearea unui meniu de navigare vizual plăcut și funcțional, care să ofere acces rapid la paginile importante ale site-ului.

**Comment by deni5-c** [comment]
`<nav>
        <div class="nav">
            <img src="img/348235784_184011931266196_8181862770752389130_n.png" alt="" class="logo">
            <div class="nav-links">
                <a href="" class="nav-link-style">Home</a>
                <a href="" class="nav-link-style">Studios</a>
                <a href="" class="nav-link-style">Contact Us</a>
            </div>
        </div>
    </nav>`
    @Staycoo10 Adauga nav-ul ca functie prin note.js
    
    Alaturi de stilizare:
[navbar.zip](https://github.com/Staycoo10/RoyalSudio/files/14896871/navbar.zip)
